require 'spec_helper'
require 'facter'
require 'facter/itop_facts'

@test_data = '{"objects":{"Server::214":{"code":0,"message":"","class":"Server","key":"214","fields":{"name":"b0e012ash1002","description":"","org_id":"2","organization_name":"Cloud Platform Eng","business_criticity":"medium","move2production":"","contacts_list":[],"documents_list":[],"applicationsolution_list":[],"providercontracts_list":[],"softwares_list":[],"tickets_list":[],"serialnumber":"DHDKCY1","location_id":"1","location_name":"DFT-ACC5","status":"Up","brand_id":"12","brand_name":"Dell","model_id":"13","model_name":"PowerEdge R720xd","asset_number":"","purchase_date":"","end_of_warranty":"","networkdevice_list":[],"physicalinterface_list":[{"name":"etho","comment":"","ipgateway":"","speed":"","ipaddress_id":"3043","ipaddress_name":"1.1.1.1","macaddress":"","ipmask":"255.255.255.255 - \/32","vlans_list":[],"mtu":"","finalclass":"PhysicalInterface","friendlyname":"etho b0e012ash1002","ipaddress_id_friendlyname":"1.1.1.1"}],"rack_id":"0","rack_name":"","enclosure_id":"0","enclosure_name":"","nb_u":"","powerA_id":"0","powerA_name":"","powerB_id":"0","powerB_name":"","fiberinterfacelist_list":[],"san_list":[],"managementip_id":"3036","managementip_name":"10.119.236.172","osfamily_id":"17","osfamily_name":"RedHat","osversion_id":"20","osversion_name":"CentOS","oslicence_id":"0","oslicence_name":"","cpu":"CPUs: 2 Cores: 32 Vendor: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz","ram":"252.23 GB","logicalvolumes_list":[],"PONumber":"","Environment":"Prod","Domain":"mgmt.symcpe.net","Virtual":"physical","HardwareArchitecture":"x86_64","KernelRelease":"2.6.32-431.el6.x86_64","Gateway":"10.119.236.1","OSRelease":"2.6.32","MgmtMACAddress":"B8:CA:3A:68:71:08","YUMAvailableUpdates":"","YUMSecurityUpdates":"","FormFactor":"Rack Mount Chassis","Timezone":"GMT","Uptime":"11 days","BIOS":"2.1.3 Dell Inc. 11\/20\/2013","Filesystems":"ext4,iso9660","VLANs":"","Netmask":"255.255.254.0","LSBRelease":"base-4.0-amd64\nbase-4.0-noarch\ncore-4.0-amd64\ncore-4.0-noarch\ngraphics-4.0-amd64\ngraphics-4.0-noarch\nprinting-4.0-amd64\nprinting-4.0-noarch","FQDN":"b0e012ash1002.mgmt.symcpe.net","Cost":"","NetBookValue":"","GLNumber":"","SwapSpace":"32767.99 MB","Role":"","DepreciationStartDate":"","notes":"","IPMI_IP":"","IPMI_Name":"","IPMI_MAC":"","finalclass":"Server","friendlyname":"b0e012ash1002","org_id_friendlyname":"Cloud Platform Eng","location_id_friendlyname":"DFT-ACC5","brand_id_friendlyname":"Dell","model_id_friendlyname":"PowerEdge R720xd","rack_id_friendlyname":"","enclosure_id_friendlyname":"","powerA_id_friendlyname":"","powerA_id_finalclass_recall":"","powerB_id_friendlyname":"","powerB_id_finalclass_recall":"","managementip_id_friendlyname":"10.119.236.172","osfamily_id_friendlyname":"RedHat","osversion_id_friendlyname":"CentOS","oslicence_id_friendlyname":""}}},"code":0,"message":"Found: 1"}'


describe 'Facter::Util::ITOP_Facts' do
    before(:each) do 
        Facter::Util::ITOP_Facts.stub(:read_cache).with().and_return(@test_data)
        Facter::Util::ITOP_Facts.stub(:write_cache).with(:any).and_return(nil)


