name    'logstash'
version '0.1.0'
source 'UNKNOWN'
author 'mahesh_nagaraj@symantec.com'
license 'Apache License, Version 2.0'
description 'This puppet module is used to setup the node for shipping logs to LMM and Cleanup Hadoop Logs every 30 Days'

